### ISSUE TITLE
worker-loader not working

### ISSUE THREAD

**Issue by stoplion** [webpack-contrib/worker-loader#181]
After Webpacking.. I'm getting two files:
`application-ef25b6635fa029f2c3d9.js`
and...
`parse_line_worker-744295acb4e2c4a5e538.js`

First file has a `postMessage` to the webworker (which is in that second file). The Webworker has an addEventListener for that `postMessage`

The postMessage is called, but the code in the Webworker is never called. In fact, it isn't even in the bundle.

Are you suppose to include both files? 

In the documentation, it isn't suggested that you include both files. And in the application file, I'm including it like so...
```
import Worker from '../utils/parser/parse_line.worker';
const parseLineWorker = new Worker();
```

There is also the "inline" option to create the worker via Blob URL. 
https://github.com/webpack-contrib/worker-loader#inline

And yet, the second 'parse_line_worker' file is still being created and the Webworker is STILL not called.

**Comment by stoplion** [comment]
reason I'm asking is because the worker is just not showing in the bundle at all.. the call to the worker `parseLineWorker.postMessage({....});` is there, but the code in the `*.worker.js` file is not

**Comment by NaLLiFFuNT** [comment]
Got similar issue
```
"webpack": "^4.29.0",
"worker-loader": "^2.0.0"
"ts-loader": "^5.3.3",
```

```typescript
import MyWorker from 'worker-loader!./fetch.worker';

const worker = new MyWorker();
worker.postMessage({type: 'init', options: {}});
```

worker file is loaded but its content never runs. Tried to send `postMessage` manually from console, got the same behaviour.

**Comment by pmkroeker** [comment]
I am getting a similar issue, inline seems to not be respected and is still outputting a file.

**Comment by stoplion** [comment]
I ended up using another worker library. `worker-loader` doesn't seem active anymore.

**Comment by timothyjellison** [comment]
@stoplion What library did you end up using?

**Comment by droberts-ada** [comment]
@timothyjellison `worker-plugin` from GoogleChromeLabs worked for me

https://github.com/GoogleChromeLabs/worker-plugin

**Comment by evilebottnawi** [comment]
You should not use `const parseLineWorker = new Worker();`, this loader do it for you. We need more examples for README, I already opened the problem

**Comment by nick4fake** [comment]
> You should not use `const parseLineWorker = new Worker();`, this loader do it for you. We need more examples for README, I already opened the problem

Well, then what should be used?

**Comment by nick4fake** [comment]
Even typescript typing example uses class, not instance:

````
declare module 'worker-loader!*' {
    class WebpackWorker extends Worker {
        constructor();
    }

    export default WebpackWorker;
}

````

**Comment by evilebottnawi** [comment]
Yes, sorry, my mistake, it is fixed in the master, will be great if you provide minimum reproducible test repo, I will add more tests to ensure we really fix your problem

**Comment by Gorizory** [comment]
@alexander-akait encountered similar problem.
Webpack creates 2 files:
`worker.bundle.worker.js` - i guess includes worker-loader code.
`worker.bundle.worker.worker.js` - actual worker code.

App fetches only `worker.bundle.worker.js` during runtime.
Here's [test repo](https://github.com/Gorizory/sandbox) which reproduces this.

**Comment by Gorizory** [comment]
Finally fixed it.
Should have deleted loader from `webpack.config.js`, [part of README](https://github.com/webpack-contrib/worker-loader#integrating-with-typescript) with TypeScript integration didn't tell it.

**Comment by RaphaelRoyerRivard** [comment]
@Gorizory I removed the `{ test: /\.worker\.ts$/, loader: "worker-loader" },` line from `webpack.config.js` and the actual worker code was still not loaded. I can see the `inference.worker.worker.js` and `inference.worker.ts` files in the Sources section of the Chrome console, but none of them contains the actual worker code.
